// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace API_Ferramenta.Models;

[Table("Prodotto")]
[Index("ProdottoCod", Name = "UQ__Prodotto__19B6175D39BE9D07", IsUnique = true)]
public partial class Prodotto
{
    [Key]
    [Column("prodottoID")]
    public int ProdottoId { get; set; }

    [Required]
    [Column("prodottoCOD")]
    [StringLength(20)]
    [Unicode(false)]
    public string ProdottoCod { get; set; }

    [Required]
    [Column("nome")]
    [StringLength(250)]
    [Unicode(false)]
    public string Nome { get; set; }

    [Column("descrizione", TypeName = "text")]
    public string Descrizione { get; set; }

    [Column("prezzo", TypeName = "decimal(18, 0)")]
    public decimal? Prezzo { get; set; }

    [Column("quantita")]
    public int? Quantita { get; set; }

    [Column("repartoRIF")]
    public int RepartoRif { get; set; }

    [ForeignKey("RepartoRif")]
    [InverseProperty("Prodottos")]
    public virtual Reparto RepartoRifNavigation { get; set; }
}