// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace API_Ferramenta.Models;

[Table("Reparto")]
[Index("Nome", "Fila", Name = "UQ__Reparto__7C26DB9F0666ACD4", IsUnique = true)]
[Index("RepartoCod", Name = "UQ__Reparto__EF6534E5D652E78C", IsUnique = true)]
public partial class Reparto
{
    [Key]
    [Column("repartoID")]
    public int RepartoId { get; set; }

    [Required]
    [Column("repartoCOD")]
    [StringLength(20)]
    [Unicode(false)]
    public string RepartoCod { get; set; }

    [Required]
    [Column("nome")]
    [StringLength(250)]
    [Unicode(false)]
    public string Nome { get; set; }

    [Required]
    [Column("fila")]
    [StringLength(20)]
    [Unicode(false)]
    public string Fila { get; set; }

    [InverseProperty("RepartoRifNavigation")]
    public virtual ICollection<Prodotto> Prodottos { get; set; } = new List<Prodotto>();
}